
#A minimal valid config is: kind and apiversion
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#Cluster wide options
#name your cluster
name: my-cluster
#featureGates specifies a map of feature names to booleans that enable or disable experimental features.
# featureCates:
  # EphemeralContainers: true
#runtime config - --runtime-config kube-apiserver flag. This may be used to e.g. disable beta / alpha APIs.
# runtimeConfig:
  # "networking.k8s.io/v1beta1": "false"
#networking
#IP familyuu
# networking:
  # ipFamily: ipv6
# Dual Stack clusters - You can run dual stack clusters using kind 0.11+, on kubernetes versions 1.20+.
networking:
  # ipFamily: Dual
  # podSubnet:
##API server - api server listen addres and port can be customized with
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
##podsubnet - The subnet used for pods
  podSubnet: "10.244.0.0/16" #default
##serviceSubnet - The subnet used for services
  serviceSubnet: "10.96.0.0/12" #default

## NODES
#nodes - list of nodes to create in the cluster
nodes:
  - role: control-plane # one node hosting a control plane
##You can create a multi node cluster with the following config:
  # - role: control-plane
  # - role: worker
  # - role: worker
  # - role: worker
##per node configuration

#extra mounts
# extraMounts:
  # - hostPath: /path/on/host
  #   containerPath: /path/in/container
  #   readOnly: true
#extra port mappings
# extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   listenAddress: "